import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider } from 'react-router-dom'
import { createAppRouter } from './app/router'
import { AppProviders, createQueryClient } from './app/providers'
import './styles.css'
import './review-fixes.css'
import './tutorials.css'
import './api-keys.css'
import './auth.css'
import './debugger.css'
import './evaluation.css'
import './releases.css'

createRoot(document.getElementById('root')!).render(<StrictMode><AppProviders queryClient={createQueryClient()}><RouterProvider router={createAppRouter()} future={{ v7_startTransition: true }} /></AppProviders></StrictMode>)
